%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\mchetry2018\Desktop\Dropbox\Manisha\DarcyB\velocity.csv
%
% Auto-generated by MATLAB on 23-Nov-2020 14:08:41

%% Setup the Import Options
clear all
clc

opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ["\t", ","];

% Specify column names and types
opts.VariableNames = ["Permeability", "Var2", "Var3", "Var4", "Var5"];
opts.SelectedVariableNames = ["Var2","Var3"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];
%opts = setvaropts(opts, [  4, 5], "WhitespaceRule", "preserve");
%opts = setvaropts(opts, [ 4, 5], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
velocity_coarse = readtable("C:\Users\mchetry2018\Desktop\Dropbox\Manisha\DarcyB\velocity_coarse.csv", opts);

save('velocity_coarse.mat','velocity_coarse');
%%

opts.VariableNames = ["Permeability", "Pressure"];
opts.SelectedVariableNames = ["Permeability"];
opts.VariableTypes = ["double", "double"];
%opts = setvaropts(opts, [  4, 5], "WhitespaceRule", "preserve");
%opts = setvaropts(opts, [ 4, 5], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Permeability_c = readtable("C:\Users\mchetry2018\Desktop\Dropbox\Manisha\DarcyB\perm_coarse.csv", opts);

save('Permeability_coarse.mat','Permeability_c');

opts.VariableNames = ["Permeability", "Var2", "Var3", "Var4", "Var5"];
opts.SelectedVariableNames = ["Var2","Var3"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];
%opts = setvaropts(opts, [  4, 5], "WhitespaceRule", "preserve");
%opts = setvaropts(opts, [ 4, 5], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
velocity_fine = readtable("C:\Users\mchetry2018\Desktop\Dropbox\Manisha\DarcyB\velocity_fine.csv", opts);

save('velocity_fine.mat','velocity_fine');


opts.VariableNames = ["Permeability", "Pressure"];
opts.SelectedVariableNames = ["Permeability"];
opts.VariableTypes = ["double", "double"];
%opts = setvaropts(opts, [  4, 5], "WhitespaceRule", "preserve");
%opts = setvaropts(opts, [ 4, 5], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Permeability_f = readtable("C:\Users\mchetry2018\Desktop\Dropbox\Manisha\DarcyB\perm.csv", opts);

save('Permeability_fine.mat','Permeability_f');

%% Clear temporary variables
clear opts